kind: pipeline
name: build
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    when:
      branch:
        - master
    environment:
      - REACT_APP_API_HOST: https://pig.vault48.org/
      - REACT_APP_REMOTE_CURRENT: https://pig.vault48.org/static/
    settings:
      dockerfile: docker/www/Dockerfile
      tag:
        - ${DRONE_BRANCH}
      custom_labels:
        - "commit=${DRONE_COMMIT_SHA}"
      username:
        from_secret: global_docker_login
      password:
        from_secret: global_docker_password
      registry:
        from_secret: global_docker_registry
      repo:
        from_secret: docker_repo
