kind: pipeline
name: build
type: docker

platform:
  os: linux
  arch: amd64

environment:
  registry:
    from_secret: global_docker_registry

steps:
  - name: build
    image: plugins/docker
    when:
      branch:
        - develop
    settings:
      dockerfile: docker/www/Dockerfile
      tag:
        - ${DRONE_BRANCH}
      custom_labels:
        commit: ${DRONE_COMMIT_SHA}
      username:
        from_secret: global_docker_login
      password:
        from_secret: global_docker_password
      registry:
        from_secret: global_docker_registry
      repo: "${registry}/${DRONE_REPO_NAME}"
