version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - ${EXPOSE}:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
